using ConsoleApp1.CSharp_Basics;
using ConsoleApp1.CSharp_Basics.Array;
using ConsoleApp1.CSharp_Basics.CallBy_Value_Reference;
using ConsoleApp1.CSharp_Basics.Conditionals;
using ConsoleApp1.CSharp_Basics.Contravariance;
using ConsoleApp1.CSharp_Basics.Covariance;
using ConsoleApp1.CSharp_Basics.DataTypes;
using ConsoleApp1.CSharp_Basics.Delegates;
using ConsoleApp1.CSharp_Basics.Delegates.Events_Demo;
using ConsoleApp1.CSharp_Basics.Delegates.Events_Demo.Eventhandler;
using ConsoleApp1.CSharp_Basics.Dictionary;
using ConsoleApp1.CSharp_Basics.Enums;
using ConsoleApp1.CSharp_Basics.ExceptionHandling;
using ConsoleApp1.CSharp_Basics.ExtensionMethods;
using ConsoleApp1.CSharp_Basics.Files_Directories;
using ConsoleApp1.CSharp_Basics.Files_Directories.LearnFileDemo;
using ConsoleApp1.CSharp_Basics.Generics;
using ConsoleApp1.CSharp_Basics.HashTable;
using ConsoleApp1.CSharp_Basics.Indexers;
using ConsoleApp1.CSharp_Basics.Initializer;
using ConsoleApp1.CSharp_Basics.Initializer.CollectionInitalizer;
using ConsoleApp1.CSharp_Basics.Initializer.ObjectInitializer;
using ConsoleApp1.CSharp_Basics.Interfaces;
using ConsoleApp1.CSharp_Basics.LINQ;
using ConsoleApp1.CSharp_Basics.LINQ.Lambda;
using ConsoleApp1.CSharp_Basics.LINQ.OFtype;
using ConsoleApp1.CSharp_Basics.LINQ.Orderby;
using ConsoleApp1.CSharp_Basics.LINQ.SyntaxandWhere;
using ConsoleApp1.CSharp_Basics.Lists;
using ConsoleApp1.CSharp_Basics.Loops;
using ConsoleApp1.CSharp_Basics.Methods;
using ConsoleApp1.CSharp_Basics.OOP;
using ConsoleApp1.CSharp_Basics.OOPS;
using ConsoleApp1.CSharp_Basics.OOPS.Encapsulation.AcessModifier;
using ConsoleApp1.CSharp_Basics.OOPS.Inheritance;
using ConsoleApp1.CSharp_Basics.OOPS.Structural_Relationships;
using ConsoleApp1.CSharp_Basics.OOPS.UpCasting;
using ConsoleApp1.CSharp_Basics.Operators;
using ConsoleApp1.CSharp_Basics.Operators.Logical_Operator;
using ConsoleApp1.CSharp_Basics.Patial_Classes;
using ConsoleApp1.CSharp_Basics.Queue;
using ConsoleApp1.CSharp_Basics.SOLID_Principles;
using ConsoleApp1.CSharp_Basics.Stacks;
using ConsoleApp1.CSharp_Basics.Strings;
using ConsoleApp1.CSharp_Basics.Structure;
using ConsoleApp1.CSharp_Basics.Tuples;
using ConsoleApp1.CSharp_Basics.UserInput;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using static ConsoleApp1.CSharp_Basics.LINQ.OFtype.student;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //StringInterpolation.Run();
            //Strings.Run();
            //User_input.Run();
            //LearnStructure.StructureDemo();
            //StringToDatetime.RunDatetime();
            //EnumDemo.Run();
            //Learn_StringBuilder.Run();
            //Classes_Obj.Run();
            //AnonymousType.Run();
            //TypeCasting.Run();
            //Variables.Run();
            //DynamicType.Run();
            //NullableType.Run();
            //By_Value.Run();
            //LearnInterfaces.Run();
            //Operator_Precedence.Run();
            //AssignmentOP.Run();
            //If_Else.Run();
            //Ternary_Operator.Run();
            //LearnSwitches.Run();
            //LearnWhile_loop.Run();
            //For_Loop.Run();
            //LearnDoWhile.Run();
            //PartialClassImpl.Run();
            //Multiple.Run();
            //Learn_Generic.Run();
            //Indexer.Run();
            //LearnList.Run();
            //SortedListDemo.Run();
            //SortListdes.Run();
            //LearnDictionary.Run();
            //LearnHashtable.Run();
            //LearnStack.Run();
            //Queuedemo.Run();
            //learnTuple.Run();
            //LearnValueTuple.Run();
            //LearnException.Run();
            //NestedException.Run();
            //Throw_Demo.Run();
            //Rethrow.Run();
            //CustomException.Run();
            //Delegates_Demo.Run();
            //MultiCast.Run();
            //Returnvalue.Run();
            //Action_key.Run();
            //Predicate_key.Run();
            //Anonymous_Method.Run();
            //Subscriber.Run();
            //Subscribe.Run();
            //Programs.Run();
            //Program2.Run();
            //UpcastingDemo.Run();
            //SizeProgram.Run();
            //CoVariance.Run();
            //ContraVariance.Run();
            //Size.Run();
            //Files.Run();
            //Directories.Run();
            //File_Demo.Run();
            //Objects.Run();
            //Collection.Run();
            //Coll_ObjInitializer.Run();
            //Bank.Run();
            //Composition.Run();
            //Aggregation.Run();
            //Association.Run();
            //Inheritance.Run();
            //Constructor.Run();
            //BaseKey.Run();
            //Type_Conversion.Run();
            //Liskov_Substitution_Principle.Run();
            //Interface_Segregation_Principle.Run();
            //Dependency_Inversion_Principle.Run();
            //Query_Syntax.Run();
            //Lambda_.Run();
            //Logic_Op.Run();
            //Method_Syntax.Run();
            //Query_OFtype.Run();
            //Method_OFType.Run();
            Query_Orderby.Run();
        }
    }
}
